### ISSUE TITLE
Tiling Designer Question

### ISSUE THREAD

**Issue by ArchivumFamiliae** [pierrebai/Alhambra#2]
Hi!  I'm enjoying playing around with this to see the infinite variations that can be created using the existing mosaics and tilings but am struggling to get the Tiling Designer to work.  This could be because I don't understand tilings _per se_ (complete dilettante!) so I'm not sure if it's an issue with me or the Designer.  Here's what I'm doing:

1. I create some polygons in a repeatable pattern (e.g. four squares to form a 2 by 2 larger square).
2. I click the button **Draw Vectors**.
3. Using the middle mouse button, I click the central point of the square in position x1 and y1.
4. I drag to the same point in the square immediately below (x1, y2).

When taking these steps in this, or any other design, nothing happens.  If I use the middle button on my mouse and click-drag without the **Draw Vectors** button selected, I get a copy of the polygon the mouse is hovering over.

Loading a pre-made tiling file shows the vectors on screen, but selecting the **Draw Vector** option and clicking removes one of the vectors, whereas the second one appears to stay in place and remain unchanged even if underlying polygons are deleted.

Is this because the design needs to fit some specific criteria before translation vectors can be drawn (if so, what are those criteria?) or is there something else that I don't understand?

**Comment by pierrebai** [comment]
Hi,

I'm on my phone right now, so I cannot try to reproduce your problem, but normally you grt to draw two vectors. If you draw more, the first one gets replaced, then the 2nd and so on.

I admit it is not super user friendly. What's more, you'll discover that you caanot save your design in the folder where the app look for tilings...

The program is unfinished in these areas, as I always use it in my build folder where everything is writable.

I haven't put any time in it for months, even years now. I should take the time to clean it up, but haven't got the courage to yet!

**Comment by pierrebai** [comment]
Hi,

I ended-up writing a fix for the tiling editor. Now the "Draw Vectors" function should work as exepcted. I also added to read tilings and mosaics from the user's Documents/tilings and Documents/mosaics folders. If you save your creations there, the program will find them when restarted.
